### ISSUE TITLE
Add support for extract values out of labels

### ISSUE THREAD

**Issue by onedr0p** [kashalls/kromgo#11]
It would be cool to add something like [label_values](https://grafana.com/docs/grafana/latest/datasources/prometheus/template-variables/) to extract values of labels.

e.g.

```
label_values(kubernetes_build_info{instance="192.168.42.10:10257"}, git_version)
```

would return `1.29.1`

**Comment by kashalls** [comment]
Thanks for the suggestion.

Added in #16.
