### ISSUE TITLE
Change default host to empty string

### ISSUE THREAD

**Issue by timtorChen** [kashalls/kromgo#75]
After upgrade from `v0.3.1` to `v0.4.0`, I found kromgo is not be able to access form the nginx. 
It seems the default value separated after summer cleaning cuase the issue.

https://github.com/kashalls/kromgo/blob/eb6302081381f04565de206f87cb667423e90da2/cmd/kromgo/init/configuration/configuration.go#L14-L18

It would be more suitable for a default use case by changing default ServerHost to an empty string "" or "0.0.0.0".

**Comment by kashalls** [comment]
Sorry, this one got lost in my box somehow... 

I can default this to be "0.0.0.0" which makes more sense. The issue with the health server though is that you don't particularly want to expose this, so this might stay as localhost. and can be configured if needed.

**Comment by timtorChen** [comment]
Never mind, thank for your awesome project.

Hmm, I have a different point of view. As the health server is designed for Prometheus to scrape, and Prometheus is typically an external server to Kromgo. Thus, I think it might make sense for the HealthHost to also default to 0.0.0.0.
